server:  port: 6060
spring:
  application:
    name: service-2
eureka:  client:    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhostmanagement:  endpoints:    web:      exposure:        include: "*"        
---spring:  profiles: deveureka:  client:    service-url:      defaultZone: http://ec2-13-209-96-55.ap-northeast-2.compute.amazonaws.com:8761/eureka/  instance:    hostname: ec2-3-34-131-92.ap-northeast-2.compute.amazonaws.com